defaults:
  - _self_

dataset: null
model: null

dataloader:
  batch_size: 16
  num_workers: 0

optimizer:
  type: adam
  lr: 0.001
  weight_decay: 1e-5

loss:
  loss_function: SpikeRate
  true_rate: 0.2
  false_rate: 0.03
  reduction: sum

training:
  epochs: 100
  skip_test: true
