_target_: evdad.data.dataset.generic_event_dataset.GenericEventDataset

train_data: /mnt/d/AI/SNN/Datasets/Highway_Traffic_Videos_Dataset/train.csv
train_labels: /mnt/d/AI/SNN/Datasets/Highway_Traffic_Videos_Dataset/train_labels.csv
test_data: /mnt/d/AI/SNN/Datasets/Highway_Traffic_Videos_Dataset/test.csv
test_labels: /mnt/d/AI/SNN/Datasets/Highway_Traffic_Videos_Dataset/test_labels.csv

img_shape: [260, 346] # HW
sampling_time: 1
sample_length: 300
reshape_spike: false

num_classes: 3