_target_: evdad.data.dataset.generic_event_dataset.GenericEventDataset

train_data: /mnt/d/AI/SNN/Datasets/Highway Traffic Videos Dataset/Highway_Traffic_Videos_Dataset_new_30_classifier/train.csv
train_labels: /mnt/d/AI/SNN/Datasets/Highway Traffic Videos Dataset/Highway_Traffic_Videos_Dataset_new_30_classifier/train_labels.csv
test_data: /mnt/d/AI/SNN/Datasets/Highway Traffic Videos Dataset/Highway_Traffic_Videos_Dataset_new_30_classifier/test.csv
test_labels: /mnt/d/AI/SNN/Datasets/Highway Traffic Videos Dataset/Highway_Traffic_Videos_Dataset_new_30_classifier/test_labels.csv

img_shape: [128, 128] # HW
sampling_time: 1
sample_length: 30

num_classes: 3