_target_: evdad.data.dataset.generic_event_dataset.GenericEventDataset

train_data: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_30_Noisy_128x128/train_small.csv
train_labels: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_30_Noisy_128x128/train_labels_small.csv
test_data: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_30_Noisy_128x128/test.csv
test_labels: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_30_Noisy_128x128/test_labels.csv

img_shape: [128, 128] # HW
sampling_time: 1
sample_length: 30

num_classes: 2