_target_: evdad.data.dataset.generic_event_dataset.GenericEventDataset

train_data: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_1_new/train.csv
train_labels: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_1_new/train_labels.csv
test_data: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_1_new/test.csv
test_labels: /mnt/d/AI/SNN/Datasets/UCSD_Anomaly_Dataset/UCSD_Anomaly_Event_Dataset_1_new/test_labels.csv

img_shape: [180, 240] # HW
sampling_time: 1
sample_length: 1

num_classes: 2