_target_: evdad.models.lava.slayer.cuba.linear_autoencoder.LinearAutoEncoder

threshold: 0.1
current_decay: 0.9
voltage_decay: 0.9
tau_grad: 1
scale_grad: 1
requires_grad: True

C: 2
H: 34
W: 34
T: 30
