defaults:
  - mlflow: local
  - train
  - dataset: HTVD
  - model: slayer_cuba_linear_autoencoder
  - _self_
  
mlflow:
  experiment_name: DEBUG
  run_name: slayer_cuba_HTVD_linear_autoencoder
  tags: {version: 0.1.0}

dataloader:
  batch_size: 4

loss:
  loss_function: MSE

dataset:
  reshape_spike: true
  data_is_label: true

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts