defaults:
  - mlflow: local
  - train
  - dataset: NMNIST
  - model: slayer_cuba_cnn_autoencoder
  - _self_
  
mlflow:
  experiment_name: SLAYER
  run_name: slayer_cuba_NMNIST_cnn_autoencoder
  tags: {version: 0.1.0}

training:
  type: SLAYER
  epochs: 200

loss:
  loss_function: SpikeTime
  time_constant: 1
  filter_order: 1

dataset:
  data_is_label: true
  reshape_spike: false

dataloader:
  batch_size: 128

optimizer:
  type: adam
  lr: 0.1

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts