defaults:
  - mlflow: local
  - train
  - dataset: NMNIST
  - model: slayer_cuba_linear_autoencoder
  - _self_
  
mlflow:
  experiment_name: SLAYER
  run_name: slayer_cuba_NMNIST_linear_autoencoder
  tags: {version: 0.1.0}

training:
  epochs: 200

dataset:
  reshape_spike: true
  data_is_label: true

loss:
  loss_function: SpikeTime
  time_constant: 1
  length: 1
  filter_order: 2
  reduction: sum

optimizer:
  type: adamw
  lr: 0.001
  weight_decay: 1e-5

dataloader:
  batch_size: 128

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts