defaults:
  - mlflow: local
  - train
  - dataset: UCSD
  - model: slayer_cuba_simple_conv
  - _self_

mlflow:
  experiment_name: DEBUG
  run_name: slayer_cuba_simple_conv
  tags: {version: 0.1.0}

training:
  type: SLAYER
  epochs: 50
  skip_test: false

dataset:
  reshape_spike: false

optimizer:
  type: adam
  lr: 0.01

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts