defaults:
  - mlflow: local
  - train
  - dataset: UCSD
  - model: slayer_cuba_simple_dense
  - _self_
  
mlflow:
  experiment_name: DEBUG
  run_name: slayer_cuba_simple_dense
  tags: {version: 0.1.0}

training:
  type: SLAYER
  epochs: 50
  skip_test: false

dataloader:
  batch_size: 32

dataset:
  reshape_spike: true

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts