defaults:
  - mlflow: local
  - train
  - dataset: HTVD
  - model: slayer_cuba_cnn_autoencoder
  - _self_
  
mlflow:
  experiment_name: DEBUG
  run_name: slayer_cuba_HTVD_cnn_autoencoder
  tags: {version: 0.1.0}

dataloader:
  batch_size: 1

loss:
  loss_function: SpikeTime
  time_constant: 1
  length: 1
  filter_order: 1
  reduction: sum

dataset:
  data_is_label: true

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts