defaults:
  - mlflow: local
  - train
  - dataset: NMNIST
  - model: slayer_cuba_cnn_autoencoder
  - _self_
  
mlflow:
  experiment_name: SLAYER
  run_name: slayer_cuba_NMNIST_cnn_autoencoder
  tags: {version: 0.1.0}

training:
  epochs: 5

dataset:
  data_is_label: true

dataloader:
  batch_size: 128

loss:
  loss_function: SpikeTime
  time_constant: 5
  length: 100
  filter_order: 1
  reduction: sum

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts