defaults:
  - mlflow: local
  - train
  - dataset: UCSD
  - model: slayer_cuba_cnn_autoencoder
  - _self_
  
mlflow:
  experiment_name: DEBUG
  run_name: slayer_cuba_UCSD_cnn_autoencoder
  tags: {version: 0.1.0}

loss:
  loss_function: MSE

dataset:
  data_is_label: true

dataloader:
  batch_size: 8

hydra:
  job:
    chdir: true
  searchpath:
    - file:///${oc.env:HOME}/evdad/src/conf/defaults
    # - file:///${oc.env:HOME}/evdad/src/conf/experiemnts